=== nkatz01/Summer-2020-TMA-xml-json-and-ajax/nkatz01_wd_tma/recipes.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" > 
 <xs:complexType name="timedActivity">
     <xs:sequence>
         <xs:element name="activityTime" type="xs:integer" minOccurs="1"/></xs:sequence> <!--We make this mandatory eventhough some recipes won't need them (eg. Fruit salad: their cooking time 
     would be 0)  that's because it's a value used for sorting and so we want to preserve this criteria even for the recipes for which it doesn't apply.-->
    <xs:attribute name="units" type="xs:string" use="required"></xs:attribute>
 </xs:complexType>
    
    
        <xs:simpleType  name="ratingType">
            <xs:restriction base="xs:positiveInteger"> 
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="5"/>
            </xs:restriction>
        </xs:simpleType>
        
    
    
     <xs:complexType name="recipeType"> 
 <xs:sequence>
     
<xs:element name="title" type="xs:string"/>
    
     
    
     
     <xs:element name="ratingWithAttr" >
     <xs:complexType >
         <xs:sequence>
         <xs:element name="rating" type="ratingType">  </xs:element>                
         </xs:sequence>
         <xs:attribute name="howManyRated" type="xs:positiveInteger" use="required"> </xs:attribute>
     </xs:complexType>  </xs:element>
     
     <xs:element name="authorType">
     <xs:complexType  >
         <xs:sequence>
         <xs:element name="author" type="xs:string" />
         </xs:sequence>  
         <xs:attribute name="authorLink" type="xs:anyURI" use="required"></xs:attribute>
     </xs:complexType></xs:element>
  
     <xs:element name="preptime" type="timedActivity"/>
     <xs:element name="cooktime" type="timedActivity" minOccurs="0" /> 
     <xs:element name="marinatingTime" type="timedActivity" minOccurs="0" />
     <xs:element name="ExtraTime" type="xs:string" minOccurs="0" />
     <xs:element name="difficultyLevel">
         <xs:simpleType>
             <xs:restriction base="xs:string">
                 <xs:enumeration value="Easy"/>
                 <xs:enumeration value="More effort"/>
                 <xs:enumeration value="Difficult"/>
             </xs:restriction>
         </xs:simpleType>
     </xs:element> 
 <xs:element name="serves" type="xs:string"/>
 <xs:element name="description" type="xs:string"/>      
 <xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="5"/>
 <xs:element name="nutritionPerServing" > 
         <xs:complexType>
            <xs:sequence>
                <xs:element name="kcal" type="xs:positiveInteger"></xs:element>
                
                <xs:element name="fat">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d+\.*\d*\d*g" />
                        </xs:restriction>
                    </xs:simpleType>
                     </xs:element>
               
                <xs:element name="saturates">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d+\.*\d*\d*g" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="carbs">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d+\.*\d*\d*g" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="sugars">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d+\.*\d*\d*g" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="fibre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d+\.*\d*\d*g" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="protein">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d+\.*\d*\d*g" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="salt">
                    <xs:simpleType >
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d+\.\d\d*g" />
                        </xs:restriction>
                    </xs:simpleType>   
                </xs:element>
                
                
            </xs:sequence> 
             <xs:attribute name="perServing" type="xs:string"></xs:attribute>
         </xs:complexType>
 </xs:element>
     <xs:element name="ingredients" minOccurs="1" maxOccurs="4">
         <xs:complexType>
             <xs:sequence>     
 <xs:element name="ingredient" type="xs:string" minOccurs="1" maxOccurs="20"/>  
             </xs:sequence>
             <xs:attribute name="id" type="xs:string" ></xs:attribute>   
         </xs:complexType>
     </xs:element>
     <xs:element name="method">
         <xs:complexType>
             <xs:sequence>     
                 <xs:element name="instruction" type="xs:string" minOccurs="2" maxOccurs="20"/>                   
             </xs:sequence>         
         </xs:complexType>
     </xs:element>
     <xs:element name="creditType">
         <xs:complexType  >
             <xs:sequence>
                 <xs:element name="credit" type="xs:string" />
             </xs:sequence>  
             <xs:attribute name="creditLink" type="xs:anyURI" use="required"></xs:attribute>
         </xs:complexType></xs:element>
     
 </xs:sequence>
     <xs:attribute name="MagazineSubscrip" type="xs:anyURI" use="required"></xs:attribute>
         <xs:attribute name="id" type="xs:positiveInteger" use="required"></xs:attribute>
         
 </xs:complexType>
    
 
    <xs:element name="recipes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recipe" type="recipeType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nkatz01/Summer-2020-TMA-xml-json-and-ajax/nkatz01_wd_tma/recipes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="http://titan.dcs.bbk.ac.uk/~nkatz01/WD/WDTMA/recipes.xsl"?>
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://titan.dcs.bbk.ac.uk/~nkatz01/WD/WDTMA/recipes.xsd">    
    <recipe id="1" MagazineSubscrip="https://www.buysubscriptions.com/print/bbc-good-food-magazine-subscription">
        <title>One-pan jerk roast chicken</title>
     
        <ratingWithAttr howManyRated="3">
            <rating>4</rating>
        </ratingWithAttr >
        <authorType authorLink="https://www.bbcgoodfood.com/chef/cassie-best">
            <author>By Cassie Best</author>
        </authorType>

         <preptime units="MINS">
             <activityTime>30</activityTime>
            </preptime>
    <cooktime units="MINS">
        <activityTime>130</activityTime>
        </cooktime>
        <marinatingTime units="MINS">
            <activityTime>120</activityTime>
        </marinatingTime>
        <difficultyLevel>Easy</difficultyLevel>
    <serves>4 - 6</serves>
        <description>Add some spice to your Sunday lunch by marinating your bird, then use the juices to create a coconut veggie curry to serve alongside</description>
        <notes>Freezable</notes>
        <notes>Gluten-free</notes>
        <nutritionPerServing>
        <kcal>651</kcal>
        <fat>35g</fat>
        <saturates>16g</saturates>
        <carbs>37g</carbs>
        <sugars>15g</sugars>
        <fibre>8g</fibre>
        <protein>43g</protein>
        <salt>0.6g</salt>
    </nutritionPerServing>
    <ingredients>
        <ingredient>1½ kg whole chicken</ingredient>
        <ingredient>2 red onions, halved, then cut into wedges, leaving the root intact</ingredient>
        <ingredient>2 red peppers, deseeded and chopped into chunks</ingredient>
        <ingredient>4 sweet potatoes
            , peeled and cut into chunks</ingredient>
        <ingredient>400g can black beans, drained and rinsed</ingredient>
        <ingredient>400ml coconut milk</ingredient>
        <ingredient>cooked rice
            , to serve</ingredient>
        <ingredient>flatbreads, to serve</ingredient>
    </ingredients>
     <ingredients id="">
         <ingredient>1 red onion, chopped into large chunks</ingredient>
         <ingredient>5 garlic cloves, peeled</ingredient>
         <ingredient>1 scotch bonnet chilli, deseeded</ingredient>
         <ingredient>3 fat green chillies, deseeded</ingredient>
         <ingredient>bunch coriander, stalks roughly chopped, and leaves reserved, to serve</ingredient>
         <ingredient>large bunch thyme
             , leaves picked</ingredient>
         <ingredient>zest and juice 2 limes
             (save the juiced halves for the chicken)</ingredient>
         <ingredient>1 tbsp honey</ingredient>
         <ingredient>2 tbsp olive or rapeseed oil
             , plus a drizzle</ingredient>
         <ingredient>½ nutmeg
             , grated</ingredient>
         <ingredient>1 tsp ground allspice</ingredient>
    </ingredients>
    <method>
        <instruction>First make the jerk paste. Put all the ingredients in a food processor, add a good pinch of salt and blend to a fine purée, adding a splash of water if the mixture is struggling to break down. Tie the legs together if you like, and put in a large flameproof roasting tin. Pour over the jerk paste and rub all over and inside the chicken. Stuff the cavity with the juiced lime halves and cover the tray with foil. Chill for up to 48 hrs or a minimum of 2 hrs.</instruction>
        <instruction>Heat oven to 200C/180C fan/gas 6. Cook the chicken for 45 mins.</instruction>
        <instruction>Take the chicken out the oven, remove the foil and carefully lift it onto a plate, pouring any juice from the cavity into the tin. Tip the onions, peppers and sweet potatoes into the tin, and season well, then toss in the tray to coat in any residual jerk paste. Put the chicken on top of the veggies and drizzle it with a little oil. Lower the oven to 180C/160C fan/gas 4 and return the roasting tin to the middle shelf, uncovered. Roast for a further 45 mins or until the vegetables are soft and the chicken is cooked through – if you have a meat thermometer, check that the temperature has reached 75C. Carefully remove the chicken from the tin, place on a plate and wrap in foil, then leave to rest.</instruction>
        <instruction>Place the roasting tin on the hob over a medium heat. Stir in the beans and coconut milk, scraping the bottom of the tin to lift off any tasty bits. Simmer until the sauce has thickened a little, then season to taste. If the sauce looks oily, skim the fat off the surface with a spoon. Put the chicken back in the pan and scatter over the coriander leaves before taking to the table. Serve with rice and flatbreads for mopping up the sauce.</instruction>
    </method>
        <creditType creditLink="https://www.bbcgoodfood.com/search/recipes/date/1427842800">
        <credit>Recipe from Good Food magazine, April 2015</credit>
    </creditType>
    </recipe>
    
    
    <recipe id="2" MagazineSubscrip="https://www.buysubscriptions.com/print/bbc-good-food-magazine-subscription">
        <title>Roast sirloin of beef</title>
        <ratingWithAttr howManyRated="11">
            <rating>5</rating>
        </ratingWithAttr >
        <authorType authorLink="https://www.bbcgoodfood.com/chef/gary-rhodes">
            <author>By Gary Rhodes</author>
        </authorType>
        <preptime units="MINS">
            <activityTime>10</activityTime>
        </preptime>
        <cooktime units="MINS">
            <activityTime>150</activityTime>
        </cooktime>
        <ExtraTime>Plus some time</ExtraTime>
        <difficultyLevel>Easy</difficultyLevel>
        <serves>6</serves>
        <description>Gary Rhodes' delicious, succulent roast beef dish is perfect for Boxing Day lunch or an alternative Christmas Day roast. Just four ingredients</description>
        
        <nutritionPerServing>
            <kcal>331</kcal>
            <fat>19g</fat>
            <saturates>8g</saturates>
            <carbs>1g</carbs>
            <sugars>0g</sugars>
            <fibre>0g</fibre>
            <protein>36g</protein>
            <salt>1.47g</salt>
        </nutritionPerServing>
        <ingredients>
            <ingredient>2 tbsp vegetable oil or beef fat</ingredient>
            <ingredient>1-1½kg/2lb 4-3lb 5oz sirloin of beef
                joint</ingredient>
            <ingredient>1 glass red wine</ingredient>
            <ingredient>400g can beef
                consommé</ingredient> 
        </ingredients>
        <method>
            <instruction>Heat oven to 200C/fan 180C/gas 6. Heat the oil or fat in a large fl ameproof roasting tin in the oven for 5-10 mins. Season the beef all over.</instruction>
            <instruction>Place the joint fat-side down in the roasting tin and put it on the hob. Sizzle to release some of the fat, then turn the beef in the fat to seal and colour it all over, about 5 mins. The joint can now be roasted, fat-side up, allowing 10-15 mins per 450g for medium-rare, 15-20 mins per 450g for medium, 20-25 mins for medium-well and 25-30 mins for well done. Turn the joint halfway through its cooking time for an even roast. Once roasted, remove the beef from the pan and leave to one side, loosely covered with foil, to rest for 15-20 mins.</instruction>
            <instruction>Meanwhile, pour off any excess fat from the roasting tin, then put the tin on a medium heat on top of the stove. Once it begins to sizzle, pour in the red wine, allowing it to boil rapidly until almost completely evaporated. Tip in the consommé and allow to simmer for 4-5 mins. This will give a light sauce, rather than a gravy (see tip, below). Simmer for a few more mins before straining through a sieve for the smoothest of fi nishes. Carve the beef into thick slices, offering the gravy separately.</instruction>
             
        </method>
        <creditType creditLink="https://www.bbcgoodfood.com/search/recipes/date/1133395200">
            <credit>Recipe from Good Food magazine, December 2005</credit>
        </creditType>
    </recipe>
    
    <recipe id="3" MagazineSubscrip="https://www.buysubscriptions.com/print/bbc-good-food-magazine-subscription">
        <title>Gooseberry crème brûlée tart</title>
        <ratingWithAttr howManyRated="5">
            <rating>5</rating>
        </ratingWithAttr >
        <authorType authorLink="https://www.bbcgoodfood.com/chef/barney-desmazery">
            <author>By Barney Desmazery</author>
        </authorType>
        <preptime units="MINS">
            <activityTime>10</activityTime>
        </preptime>
        <cooktime units="MINS">
            <activityTime>80</activityTime>
        </cooktime>
         
        <difficultyLevel>More effort</difficultyLevel>
        <serves>8</serves>
        <description>Seasonal berries and sweet pastry make a stunning dessert for a dinner party - blowtorch for a beautifully crisp cracked sugar topping</description>
        
        <nutritionPerServing>
            <kcal>467</kcal>
            <fat>21g</fat>
            <saturates>11g</saturates>
            <carbs>60g</carbs>
            <sugars>39g</sugars>
            <fibre>3g</fibre>
            <protein>7g</protein>
            <salt>0.4g</salt>
        </nutritionPerServing>
        <ingredients>
            <ingredient>450g gooseberries</ingredient>
            <ingredient>200g white caster sugar</ingredient>
            <ingredient>4 eggs</ingredient>
            <ingredient>100ml double cream</ingredient> 
            <ingredient>500g block sweet pastry</ingredient>
            <ingredient>flour, for dusting</ingredient>
        </ingredients>
        <method>
